trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'
    - '*.md'
  tags:
    include:
    - v*
pr:
  paths:
    exclude:
    - 'docs/*'
    - '*.md'

stages:
- stage: test_and_validate
  displayName: 'Validate and Test'
  pool:
    vmImage: 'ubuntu-20.04'
  jobs:
  - job: 'Validate'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
    - script: |
        pip install flake8
        python -m flake8 fastapi_extras --count --select=E901,E999,F821,F822,F823 --show-source --statistics
      displayName: 'flake8'
  - job: 'Test'
    dependsOn: 'Validate'
    strategy:
      matrix:
        Python36Linux:
          imageName: 'ubuntu-20.04'
          python.version: '3.6'
        Python37Linux:
          imageName: 'ubuntu-20.04'
          python.version: '3.7'
        Python38Linux:
          imageName: 'ubuntu-20.04'
          python.version: '3.8'
        Python39Linux:
          imageName: 'ubuntu-20.04'
          python.version: '3.9'
      maxParallel: 4

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
	      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
        poetry install
        poetry run pytest tests
      displayName: 'Install dependencies'
    - script: |
        bash scripts/test.sh
      displayName: Test
    - script: |
        bash <(curl -s https://codecov.io/bash)
      displayName: codecov.io
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
- stage: Publish
  displayName: 'Publish to PyPI'
  dependsOn: test_and_validate
  condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags'))
  pool:
    vmImage: 'ubuntu-20.04'
  jobs:
    - job: 'Publish'
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
      - script: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 - && poetry install
          poetry build
          # poetry publish
        displayName: 'Install dependencies'
      - script: |
          bash scripts/deploy.sh
        displayName: Deploy
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: $(POETRY_HTTP_BASIC_PYPI_USERNAME)
          POETRY_HTTP_BASIC_PYPI_PASSWORD: $(POETRY_HTTP_BASIC_PYPI_PASSWORD)